package objs;
// Generated Aug 29, 2018 3:29:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Agency generated by hbm2java
 */
public class Agency  implements java.io.Serializable {


     private Integer id;
     private Location location;
     private String name;
     private String contact;
     private Set intercitylines = new HashSet(0);

    public Agency() {
    }

	
    public Agency(Location location, String name, String contact) {
        this.location = location;
        this.name = name;
        this.contact = contact;
    }
    public Agency(Location location, String name, String contact, Set intercitylines) {
       this.location = location;
       this.name = name;
       this.contact = contact;
       this.intercitylines = intercitylines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Set getIntercitylines() {
        return this.intercitylines;
    }
    
    public void setIntercitylines(Set intercitylines) {
        this.intercitylines = intercitylines;
    }




}


