package objs;
// Generated Aug 29, 2018 3:29:04 PM by Hibernate Tools 4.3.1



/**
 * Citylinedrivers generated by hbm2java
 */
public class Citylinedrivers  implements java.io.Serializable {


     private Integer id;
     private Cityline cityline;
     private Driver driver;

    public Citylinedrivers() {
    }

    public Citylinedrivers(Cityline cityline, Driver driver) {
       this.cityline = cityline;
       this.driver = driver;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cityline getCityline() {
        return this.cityline;
    }
    
    public void setCityline(Cityline cityline) {
        this.cityline = cityline;
    }
    public Driver getDriver() {
        return this.driver;
    }
    
    public void setDriver(Driver driver) {
        this.driver = driver;
    }




}


