package objs;
// Generated Aug 29, 2018 3:29:04 PM by Hibernate Tools 4.3.1



/**
 * Citystop generated by hbm2java
 */
public class Citystop  implements java.io.Serializable {


     private Integer id;
     private Cityline cityline;
     private int number;
     private String name;

    public Citystop() {
    }

    public Citystop(Cityline cityline, int number, String name) {
       this.cityline = cityline;
       this.number = number;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cityline getCityline() {
        return this.cityline;
    }
    
    public void setCityline(Cityline cityline) {
        this.cityline = cityline;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


