package objs;
// Generated Aug 29, 2018 3:29:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Citylinetimetable generated by hbm2java
 */
public class Citylinetimetable  implements java.io.Serializable {


     private Integer id;
     private Cityline cityline;
     private Date time;

    public Citylinetimetable() {
    }

    public Citylinetimetable(Cityline cityline, Date time) {
       this.cityline = cityline;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cityline getCityline() {
        return this.cityline;
    }
    
    public void setCityline(Cityline cityline) {
        this.cityline = cityline;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


