package objs;
// Generated Aug 29, 2018 3:29:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private Date birthdate;
     private int startyear;
     private int availability;
     private Set citylinedriverses = new HashSet(0);
     private Set intercitylines = new HashSet(0);

    public Driver() {
    }

	
    public Driver(String firstname, String lastname, Date birthdate, int startyear, int availability) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.birthdate = birthdate;
        this.startyear = startyear;
        this.availability = availability;
    }
    public Driver(String firstname, String lastname, Date birthdate, int startyear, int availability, Set citylinedriverses, Set intercitylines) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.birthdate = birthdate;
       this.startyear = startyear;
       this.availability = availability;
       this.citylinedriverses = citylinedriverses;
       this.intercitylines = intercitylines;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public int getStartyear() {
        return this.startyear;
    }
    
    public void setStartyear(int startyear) {
        this.startyear = startyear;
    }
    public int getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(int availability) {
        this.availability = availability;
    }
    public Set getCitylinedriverses() {
        return this.citylinedriverses;
    }
    
    public void setCitylinedriverses(Set citylinedriverses) {
        this.citylinedriverses = citylinedriverses;
    }
    public Set getIntercitylines() {
        return this.intercitylines;
    }
    
    public void setIntercitylines(Set intercitylines) {
        this.intercitylines = intercitylines;
    }




}


