package objs;
// Generated Aug 29, 2018 3:29:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Intercitystop generated by hbm2java
 */
public class Intercitystop  implements java.io.Serializable {


     private Integer id;
     private Intercityline intercityline;
     private Date arrivaltime;
     private int number;
     private String name;

    public Intercitystop() {
    }

    public Intercitystop(Intercityline intercityline, Date arrivaltime, int number, String name) {
       this.intercityline = intercityline;
       this.arrivaltime = arrivaltime;
       this.number = number;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Intercityline getIntercityline() {
        return this.intercityline;
    }
    
    public void setIntercityline(Intercityline intercityline) {
        this.intercityline = intercityline;
    }
    public Date getArrivaltime() {
        return this.arrivaltime;
    }
    
    public void setArrivaltime(Date arrivaltime) {
        this.arrivaltime = arrivaltime;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


