package objs;
// Generated Aug 29, 2018 3:29:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private String city;
     private String municipality;
     private String address;
     private Set agencies = new HashSet(0);
     private Set users = new HashSet(0);

    public Location() {
    }

	
    public Location(String city, String municipality, String address) {
        this.city = city;
        this.municipality = municipality;
        this.address = address;
    }
    public Location(String city, String municipality, String address, Set agencies, Set users) {
       this.city = city;
       this.municipality = municipality;
       this.address = address;
       this.agencies = agencies;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getMunicipality() {
        return this.municipality;
    }
    
    public void setMunicipality(String municipality) {
        this.municipality = municipality;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getAgencies() {
        return this.agencies;
    }
    
    public void setAgencies(Set agencies) {
        this.agencies = agencies;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


