package objs;
// Generated Aug 28, 2018 2:40:32 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String firstname;
     private String lastname;
     private String passhash;
     private String address;
     private String birthdate;
     private String contact;
     private String category;
     private String email;

    public User() {
    }

	
    public User(String username, String firstname, String lastname, String passhash, String address, String birthdate, String contact, String category) {
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.passhash = passhash;
        this.address = address;
        this.birthdate = birthdate;
        this.contact = contact;
        this.category = category;
    }
    public User(String username, String firstname, String lastname, String passhash, String address, String birthdate, String contact, String category, String email) {
       this.username = username;
       this.firstname = firstname;
       this.lastname = lastname;
       this.passhash = passhash;
       this.address = address;
       this.birthdate = birthdate;
       this.contact = contact;
       this.category = category;
       this.email = email;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPasshash() {
        return this.passhash;
    }
    
    public void setPasshash(String passhash) {
        this.passhash = passhash;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


